server.port=8081
spring.application.name=auraskill-api
spring.datasource.url=jdbc:postgresql://localhost:5432/auraskill
spring.datasource.username=guiassys
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.flyway.enabled=true
spring.security.oauth2.resourceserver.jwt.issuer-uri=http://keycloak:8080/realms/auraskill