name: Backend Deploy

on:
  push:
    branches:
      - main
      - hml

jobs:
  deploy:
    name: Build and Deploy API
    runs-on: self-hosted

    steps:
      # Passo 1: Checkout direto na raiz do workspace do Runner para evitar confusão de pastas
      - name: Checkout API Code
        uses: actions/checkout@v4

      # Passo 2: Define o contexto correto e aponta para o Compose da Infra
      - name: Build and Restart API Container
        run: |
          export AURA_API_PATH="${{ github.workspace }}"

          docker compose \
            --env-file /home/guiassys/devtools/repos/aura-infra/docker/hml/.env \
            -f /home/guiassys/actions-runner/_work/aura-infra/aura-infra/docker/hml/docker-compose.yml \
            --project-directory ${{ github.workspace }} \
            up -d --build auraskill-api

      # Passo 3: Limpeza de cache e imagens antigas
      - name: Clean up old images
        run: |
          docker image prune -f
          docker builder prune -f